version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: matrica_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: matrica_redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: matrica_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
